server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/AlexGod05/config-service
          search-paths: config-data
