server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    zipkin: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*)

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
mail:
  sender:
    email: proyectomailsender@gmail.com
    password: "drsa mfpw hlmp fdyz"
