server:
  port: 0

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
mail:
  sender:
    email: proyectomailsender@gmail.com
    password: "drsa mfpw hlmp fdyz"
