server:
  port: 0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: mail-sender

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
mail:
  sender:
    email: proyectomailsender@gmail.com
    password: "drsa mfpw hlmp fdyz"
